/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.novanex.vendingMachine.gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.novanex.vendingMachine.Admin.AdminComponnentWindow;
import lk.novanex.vendingMachine.Admin.Admin_Analysis;
import lk.novanex.vendingMachine.Admin.Admin_User;
import lk.novanex.vendingMachine.model.CheckCard;

/**
 *
 * @author Madusanka
 */
public class MadusankaTest extends javax.swing.JFrame {

    /**
     * Creates new form MadusankaTest
     *
     * @throws java.lang.InterruptedException
     * @throws java.text.ParseException
     */
    public MadusankaTest() throws InterruptedException, ParseException {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
//        CheckCard cc = new CheckCard();
//        cc.scanCard();
//        System.out.println(compareDate("2025-12-20"));
//        cc.cardSearching = false;
        Admin_User an = new Admin_User();
        AdminComponnentWindow acw = new AdminComponnentWindow(an);
        this.add(acw);

       
    }

//    private void startThread()  {
//
//        Thread t = new Thread(new Runnable() {
//            int i = 0;
//            @Override
//            public void run() {
//                while (i < 100) {
//                    System.out.println(i);
//                    i += 1;
//                }
//            }
//        });
//
//        t.start();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MadusankaTest().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MadusankaTest.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(MadusankaTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
