/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.novanex.vendingMachine.gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JPanel;
import lk.novanex.vendingMachine.panel.CartItem;

/**
 *
 * @author Madusanka
 */
public class madusankaTest extends javax.swing.JFrame {

    /**
     * Creates new form madusankaTest
     */
    public madusankaTest() {
        initComponents();        
//      jPanel1.setBackground(new Color(245, 245, 245));                  
//      CartItem ci = new CartItem();
//      jPanel1.add(ci);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product3 = new lk.novanex.vendingMachine.panel.Product();
        product7 = new lk.novanex.vendingMachine.panel.Product();
        product5 = new lk.novanex.vendingMachine.panel.Product();
        product4 = new lk.novanex.vendingMachine.panel.Product();
        product6 = new lk.novanex.vendingMachine.panel.Product();
        product2 = new lk.novanex.vendingMachine.panel.Product();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3, 50, 50));
        getContentPane().add(product3);
        getContentPane().add(product7);
        getContentPane().add(product5);
        getContentPane().add(product4);
        getContentPane().add(product6);
        getContentPane().add(product2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new madusankaTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.novanex.vendingMachine.panel.Product product2;
    private lk.novanex.vendingMachine.panel.Product product3;
    private lk.novanex.vendingMachine.panel.Product product4;
    private lk.novanex.vendingMachine.panel.Product product5;
    private lk.novanex.vendingMachine.panel.Product product6;
    private lk.novanex.vendingMachine.panel.Product product7;
    // End of variables declaration//GEN-END:variables
}
