/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.novanex.vendingMachine.panel;

/**
 *
 * @author Madusanka
 */
public class NormalProductView extends javax.swing.JPanel {

    /**
     * Creates new form NormalProductView
     */
    public NormalProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product1 = new lk.novanex.vendingMachine.panel.Product();
        product5 = new lk.novanex.vendingMachine.panel.Product();
        product4 = new lk.novanex.vendingMachine.panel.Product();
        product3 = new lk.novanex.vendingMachine.panel.Product();
        product6 = new lk.novanex.vendingMachine.panel.Product();
        product2 = new lk.novanex.vendingMachine.panel.Product();

        setLayout(new java.awt.GridLayout(2, 3, 1, 1));
        add(product1);
        add(product5);
        add(product4);
        add(product3);
        add(product6);
        add(product2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lk.novanex.vendingMachine.panel.Product product1;
    private lk.novanex.vendingMachine.panel.Product product2;
    private lk.novanex.vendingMachine.panel.Product product3;
    private lk.novanex.vendingMachine.panel.Product product4;
    private lk.novanex.vendingMachine.panel.Product product5;
    private lk.novanex.vendingMachine.panel.Product product6;
    // End of variables declaration//GEN-END:variables
}
