/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.novanex.vendingMachine.panel;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author ASUS
 */
public class ProductCard extends javax.swing.JPanel {

    /**
     * Creates new form ProductCard
     */
    public ProductCard() {
        initComponents();
        init();
    }
    
    private void init(){
    this.putClientProperty(FlatClientProperties.STYLE, "arc:22");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        offerTag1 = new lk.novanex.vendingMachine.component.OfferTag();
        roundPanel2 = new Componnent.RoundPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout offerTag1Layout = new javax.swing.GroupLayout(offerTag1);
        offerTag1.setLayout(offerTag1Layout);
        offerTag1Layout.setHorizontalGroup(
            offerTag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        offerTag1Layout.setVerticalGroup(
            offerTag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(480, 330));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel2.setPreferredSize(new java.awt.Dimension(450, 300));
        roundPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 80));
        roundPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, -1, -1));

        add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private lk.novanex.vendingMachine.component.OfferTag offerTag1;
    private Componnent.RoundPanel roundPanel2;
    // End of variables declaration//GEN-END:variables
}
